---
services:
  gluetun:
    image: qmcgaw/gluetun
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - SERVER_CITIES=Amsterdam,Berlin,Zurich
    ports:
      - 8080:8080/tcp # qBittorrent
      - 8080:8080 # qBittorrent
      - 6881:6881
      - 6881:6881/udp
      - 7878:7878 # Radarr
      - 9696:9696 # Prowlarr
      - 8191:8191 # Flaresolver
      - 8989:8989 # Sonarr
      - 6767:6767 # Bazarr
      - 8096:8096 # Jellyfin
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
      - 6969:6969 # Whisparr
      - 5055:5055 # Jellyseerr
    volumes:
      - /home/def/Data/Mega/Data/Code/default/config/gluetun/config:/config:Z
    secrets:
      - openvpn_user
  
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    volumes:
      - /home/def/Data/Mega/Data/Code/default/config/bazarr/config:/config:Z
      - /home/def/Backup/Torrent/Peliculas:/Peliculas:z #optional
      - /home/def/Backup/Torrent/Series:/Series:z #optional
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    #runtime: nvidia
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=http://192.168.18.97 #optional
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /home/def/Data/Mega/Data/Code/default/config/jellyfin/config:/config:Z
      - /home/def/Backup/Torrent/Series:/Series:z
      - /home/def/Backup/Torrent/Peliculas:/Peliculas:z
      - /home/def/Backup/Torrent/Porn:/Porn:z
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    volumes:
      - /home/def/Data/Mega/Data/Code/default/config/prowlarr/config:/config:Z
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    volumes:
      - /home/def/Data/Mega/Data/Code/default/config/qbittorrent/config:/config:Z
      - /home/def/Backup/Torrent/Peliculas:/Peliculas:z #optional
      - /home/def/Backup/Torrent/Series:/Series:z #optional
      - /home/def/Backup/Torrent/Porn:/Porn:z #optional
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    volumes:
      - /home/def/Data/Mega/Data/Code/default/config/radarr/config:/config:Z
      - /home/def/Backup/Torrent/Peliculas:/Peliculas:z #optional
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    volumes:
      - /home/def/Data/Mega/Data/Code/default/config/sonarr/config:/config:Z
      - /home/def/Backup/Torrent/Series:/Series:z #optional
    restart: unless-stopped

  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    volumes:
      - /home/def/Data/Mega/Data/Code/default/config/whisparr/config:/config:Z
      - /home/def/Backup/Torrent/Porn:/Porn:z #optional
    restart: unless-stopped

secrets:
  openvpn_user:
    file: ./config/gluetun/config/secrets.txt
